### ISSUE TITLE
Loading Dictionary files from file system fail

### ISSUE THREAD

**Issue by FreeTrade** [vavilon-js/vavilon.js#31]
## Description
When testing a website from the filesystem (file:/// as opposed to by http/https), dictionary files fail to load

 - `vavilon.js` version: v1.1.0
- desktop

It would be useful when testing out new translations if there was a way vavilon could load the dictionary files direct from the file system.

**Comment by kytta** [comment]
It is not a bug, but rather a needed compromise due to the way browsers load files. When deployed to a real server or a serverless environment, this bug will not be present.

To test your website locally please refer to using HTTP servers like, for example, [`sirv`](https://github.com/lukeed/sirv) or [`serve`](https://github.com/vercel/serve).

**Comment by FreeTrade** [comment]
I understand. However, it is possible to load .css/.js files from the filesystem by changing the properties of header tags. I'm sure the json files could be loaded this way too. This would be a helpful addition to vavilon as vavilon is targeted at the type of simple sites that will be developed and loaded from the filesystem without the complication of a http server.

**Comment by kytta** [comment]
Yes, but the websites are not only meant to be stored on a local computer. When they're on the web, there always is a server.

Believe me, I have tried to simplify the testing process of my websites. I have spent quite some time trying to load JSON from a filesystem and I failed; it seems it can't be done :(

**Comment by FreeTrade** [comment]
Ok thanks. I'll also look into it, maybe another approach I'll try is changing .json to .js files, although this would probably have other issues. It's important for my use case that the site should load from the filesystem as well as from a server. And thanks for Vavilon btw!
